# Generated by Django 2.1 on 2018-08-17 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_tweet_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('published_tweet_id', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'New'), (2, 'Processing'), (3, 'Published')], default=1)),
                ('type', models.SmallIntegerField(choices=[(1, 'Mention'), (2, 'Hashtag Reply')])),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
