# Generated by Django 2.1 on 2018-08-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedtweet',
            name='reply_job_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='processedtweet',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'New'), (2, 'Processing'), (3, 'Published'), (4, 'Failed')], default=1),
        ),
    ]
