# Generated by Django 2.1 on 2018-09-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180816_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedtweet',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
