# Generated by Django 2.1 on 2018-09-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_processedtweet_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedtweet',
            name='error_message',
            field=models.TextField(default=''),
        ),
    ]
